-- Add new door type columns to existing doors_inventory table
ALTER TABLE public.doors_inventory 
ADD COLUMN IF NOT EXISTS type_d100 INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS type_d82 INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS type_d80 INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS type_d_rhk INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS type_d6 INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS type_d7 INTEGER NOT NULL DEFAULT 0;